name: Update Nodes

on:
  schedule:
    - cron: "0 */8 * * *"

  workflow_dispatch:


permissions:
  contents: write


jobs:

  update:

    runs-on: ubuntu-latest


    steps:

    - name: Checkout
      uses: actions/checkout@v4


    - name: Install
      run: |
        pip install requests pyyaml

        wget -q https://github.com/SagerNet/sing-box/releases/latest/download/sing-box-linux-amd64.tar.gz

        tar -xzf sing-box-linux-amd64.tar.gz

        sudo mv sing-box-*/sing-box /usr/local/bin/sing-box

        sing-box version


    - name: Check nodes
      run: |
        python checker.py


    - name: Save
      run: |

        git config user.name github-actions

        git config user.email github-actions@github.com

        git add nodes.txt sub.txt

        git commit -m "update alive nodes" || true

        git push
